# Generated by Django 2.0.3 on 2018-04-09 19:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='gamestate',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='options',
        ),
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GameOptions',
        ),
        migrations.AddField(
            model_name='item',
            name='game_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.GameState'),
        ),
    ]
