# Generated by Django 2.0.3 on 2018-04-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_payment_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.Game'),
        ),
    ]
