# Generated by Django 2.0.3 on 2018-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_auto_20180409_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='game_state',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='score',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
