# Generated by Django 2.0.2 on 2018-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_auto_20180324_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
