# Generated by Django 2.0.2 on 2018-03-23 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestore', '0003_auto_20180324_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='value',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gamestore.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='https://nyrio.github.io/flappy-bee/'),
            preserve_default=False,
        ),
    ]
