# Generated by Django 2.0.3 on 2018-04-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0004_auto_20180410_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['value']},
        ),
    ]
