# Generated by Django 2.0.3 on 2018-04-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0005_game_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-value']},
        ),
    ]
