# Generated by Django 2.0.2 on 2018-04-15 14:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0006_auto_20180415_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=cloudinary.models.CloudinaryField(default='sample', max_length=255, verbose_name='cover'),
            preserve_default=False,
        ),
    ]
