# Generated by Django 2.0.2 on 2018-04-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0008_auto_20180417_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='player',
            new_name='user',
        ),
    ]
